# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0hzgfGLOCIC4Z0wXnwccCQ8Zjlb39Fl
"""

!pip install transformers datasets accelerate scikit-learn scipy

import pandas as pd

df = pd.read_csv("mentalmanip_en.csv")

# Keep only manipulative
df = df[df["Manipulative"] == 1]

df.head()

def map_emotion(techniques):
    if pd.isna(techniques):
        return None

    t = techniques.lower()

    if any(x in t for x in ["victim", "servant"]):
        return "guilt"
    elif any(x in t for x in ["shaming", "accusation"]):
        return "shame"
    elif any(x in t for x in ["intimidation", "anger"]):
        return "threat"
    elif "persuasion" in t or "seduction" in t:
        return "flattery"
    else:
        return None  # drop others

df["emotion"] = df["Technique"].apply(map_emotion)

# Drop rows with None
df = df.dropna(subset=["emotion"])

df["emotion"].value_counts()

label_map = {
    "guilt": 0,
    "shame": 1,
    "threat": 2,
    "flattery": 3
}

df["label"] = df["emotion"].map(label_map)

from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(df, test_size=0.1, stratify=df["label"])

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")

from datasets import Dataset

train_ds = Dataset.from_pandas(train_df[["Dialogue", "label"]])
val_ds = Dataset.from_pandas(val_df[["Dialogue", "label"]])

def tokenize(example):
    return tokenizer(example["Dialogue"], truncation=True, padding="max_length", max_length=128)

train_ds = train_ds.map(tokenize, batched=True)
val_ds = val_ds.map(tokenize, batched=True)

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "xlm-roberta-base",
    num_labels=4
)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./emotion_model",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    learning_rate=2e-5,
    eval_strategy="epoch",
    save_strategy="epoch",
    fp16=True,
    logging_dir="./logs"
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds
)

trainer.train()

df_multi = pd.read_csv("mentalmanip_master.csv")

df_multi.head()

import torch
import torch.nn.functional as F

def get_probs(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=128).to("cuda")
    outputs = model(**inputs)
    probs = F.softmax(outputs.logits, dim=1)
    return probs.detach().cpu().numpy()[0]

model.to("cuda")

results = []

for _, row in df_multi.iterrows():
    p_eng = get_probs(row["dialogue_en"])
    p_hin = get_probs(row["dialogue_hi_latn"])
    p_tel = get_probs(row["dialogue_te_latn"])
    p_tam = get_probs(row["dialogue_ta_latn"])

    results.append((p_eng, p_hin, p_tel, p_tam))

from scipy.spatial.distance import jensenshannon
import numpy as np

jsd_hin, jsd_tel, jsd_tam = [], [], []

for p_eng, p_hin, p_tel, p_tam in results:
    jsd_hin.append(jensenshannon(p_eng, p_hin))
    jsd_tel.append(jensenshannon(p_eng, p_tel))
    jsd_tam.append(jensenshannon(p_eng, p_tam))

print("Hindi Drift:", np.mean(jsd_hin))
print("Telugu Drift:", np.mean(jsd_tel))
print("Tamil Drift:", np.mean(jsd_tam))

def entropy(p):
    return -np.sum(p * np.log(p + 1e-9))

entropies = [entropy(p[0]) for p in results]  # English

print("Avg Entropy:", np.mean(entropies))

dialogue_jsd_df = pd.DataFrame({
    'ID': df_multi['ID'],
    'jsd_english_hindi': jsd_hin,
    'jsd_english_telugu': jsd_tel,
    'jsd_english_tamil': jsd_tam
})

print("JSD values for each dialogue:")
display(dialogue_jsd_df.head())

dialogue_jsd_df.to_csv('dialogue_jsd_values.csv', index=False)
print("JSD values for each dialogue saved to dialogue_jsd_values.csv")

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import numpy as np

def evaluate_model(trainer, dataset):
    preds_output = trainer.predict(dataset)

    preds = np.argmax(preds_output.predictions, axis=1)
    labels = preds_output.label_ids

    acc = accuracy_score(labels, preds)
    f1_macro = f1_score(labels, preds, average='macro')
    f1_per_class = f1_score(labels, preds, average=None)

    print("Accuracy:", acc)
    print("Macro F1:", f1_macro)
    print("F1 per class:", f1_per_class)

    print("\nClassification Report:\n")
    print(classification_report(labels, preds))

    print("\nConfusion Matrix:\n")
    print(confusion_matrix(labels, preds))

# Run evaluation
evaluate_model(trainer, val_ds)

trainer.save_model("emotion_model_final")
tokenizer.save_pretrained("emotion_model_final")

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained("emotion_model_final")
model = AutoModelForSequenceClassification.from_pretrained("emotion_model_final")
model.to(device)
model.eval()

import torch.nn.functional as F

def get_probs(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=128).to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    probs = F.softmax(outputs.logits, dim=1)
    return probs.cpu().numpy()[0]

import pandas as pd

df_multi = pd.read_csv("mentalmanip_master.csv")
df_multi.head()

results = []

for _, row in df_multi.iterrows():
    p_eng = get_probs(row["dialogue_en"])
    p_hin = get_probs(row["dialogue_hi_latn"])
    p_tel = get_probs(row["dialogue_te_latn"])
    p_tam = get_probs(row["dialogue_ta_latn"])

    results.append((p_eng, p_hin, p_tel, p_tam))

conf_eng = [max(p[0]) for p in results]
print("Avg confidence:", np.mean(conf_eng))

import matplotlib.pyplot as plt

plt.boxplot([jsd_hin, jsd_tel, jsd_tam], labels=["Hindi", "Telugu", "Tamil"])
plt.title("Emotion Drift Comparison")
plt.ylabel("JSD")
plt.show()

dialogue_jsd_df = pd.DataFrame({
    'ID': df_multi['ID'],
    'jsd_english_hindi': jsd_hin,
    'jsd_english_telugu': jsd_tel,
    'jsd_english_tamil': jsd_tam
})

df_combined = df_jsd.merge(df_phase1, on="ID")

df_emotion_drift = pd.DataFrame({
    "ID": df_multi["ID"],
    "jsd_hindi": jsd_hin,
    "jsd_telugu": jsd_tel,
    "jsd_tamil": jsd_tam
})

df_emotion_drift.to_csv("emotion_drift_results.csv", index=False)

df_emotion_drift["avg_drift"] = (
    df_emotion_drift["jsd_hindi"] +
    df_emotion_drift["jsd_telugu"] +
    df_emotion_drift["jsd_tamil"]
) / 3

high_drift = df_emotion_drift.sort_values("avg_drift", ascending=False).head(10)
print(high_drift)

import numpy as np

p_eng_all = np.array([r[0] for r in results])
p_hin_all = np.array([r[1] for r in results])
p_tel_all = np.array([r[2] for r in results])
p_tam_all = np.array([r[3] for r in results])

print("Avg ENG probs:", np.mean(p_eng_all, axis=0))
print("Avg TEL probs:", np.mean(p_tel_all, axis=0))

print("Avg HIN probs:", np.mean(p_hin_all, axis=0))
print("Avg TAM probs:", np.mean(p_tam_all, axis=0))

high_drift_text = df_multi.merge(high_drift, on="ID")
print(high_drift_text[["ID", "dialogue_en"]].head())

import matplotlib.pyplot as plt

plt.hist(df_emotion_drift["avg_drift"], bins=50)
plt.title("Distribution of Emotion Drift")
plt.xlabel("JSD")
plt.ylabel("Frequency")
plt.show()