# -*- coding: utf-8 -*-
"""thesis-phase1-multiple-models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKltND4uguiSdmN5eP4NWsU9SspcbVYZ
"""

!pip install transformers datasets accelerate scikit-learn pandas numpy scipy

import pandas as pd
import numpy as np
import torch, gc, os
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification, Trainer, TrainingArguments
from torch.utils.data import Dataset
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from scipy.spatial.distance import jensenshannon
from sklearn.metrics.pairwise import cosine_similarity

train_df = pd.read_csv("train.csv")
val_df   = pd.read_csv("val.csv")
test_df  = pd.read_csv("test.csv")
full_df  = pd.read_csv("processed_data.csv")

class TextDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __len__(self):
        return len(self.labels)
    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

def clear_gpu():
    gc.collect()
    torch.cuda.empty_cache()

def train_and_save(model_name, save_name, use_fp16=True):
    clear_gpu()

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

    train_enc = tokenizer(list(train_df['english_text']), truncation=True, padding=True)
    val_enc   = tokenizer(list(val_df['english_text']), truncation=True, padding=True)

    train_ds = TextDataset(train_enc, list(train_df['manipulative_label']))
    val_ds   = TextDataset(val_enc, list(val_df['manipulative_label']))

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=1)
        probs = torch.softmax(torch.tensor(logits), dim=1)[:,1].numpy()
        return {
            "accuracy": accuracy_score(labels, preds),
            "f1": f1_score(labels, preds),
            "roc_auc": roc_auc_score(labels, probs)
        }

    training_args = TrainingArguments(
        output_dir=save_name,
        num_train_epochs=2,
        per_device_train_batch_size=2,
        per_device_eval_batch_size=2,
        gradient_accumulation_steps=2,
        fp16=use_fp16,
        eval_strategy="epoch",
        save_strategy="no"
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics
    )

    trainer.train()

    os.makedirs(save_name, exist_ok=True)
    model.save_pretrained(save_name)
    tokenizer.save_pretrained(save_name)

    print(f"Saved {save_name}")
    return save_name

xlmr_path = train_and_save("FacebookAI/xlm-roberta-base", "xlmr_model", use_fp16=True)

mbert_path = train_and_save("bert-base-multilingual-cased", "mbert_model", use_fp16=True)

deberta_path = train_and_save("microsoft/mdeberta-v3-base", "deberta_model", use_fp16=False)

def load_model(path):
    tokenizer = AutoTokenizer.from_pretrained(path)
    model = AutoModelForSequenceClassification.from_pretrained(path)
    return tokenizer, model

tok_xlmr, model_xlmr = load_model("xlmr_model")
tok_mbert, model_mbert = load_model("mbert_model")
# tok_deberta, model_deberta = load_model("deberta_model")

def get_embeddings(texts, tokenizer, model):
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    all_embs = []
    for i in range(0, len(texts), 16):
        batch = texts[i:i+16]
        inputs = tokenizer(batch, padding=True, truncation=True, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = model.base_model(**inputs)
            emb = outputs.last_hidden_state.mean(dim=1).cpu().numpy()
        all_embs.append(emb)
    return np.vstack(all_embs)

emb_xlmr, emb_mbert= {}, {}

for col in ["english_text","hindi_translit","tamil_translit","telugu_translit"]:
    emb_xlmr[col] = get_embeddings(full_df[col].tolist(), tok_xlmr, model_xlmr)
    # emb_mbert[col] = get_embeddings(full_df[col].tolist(), tok_mbert, model_mbert)
    # emb_deberta[col] = get_embeddings(full_df[col].tolist(), tok_deberta, model_deberta)

def get_probs(texts, tokenizer, model):
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    all_probs = []
    for i in range(0, len(texts), 16):
        batch = texts[i:i+16]
        inputs = tokenizer(batch, padding=True, truncation=True, return_tensors="pt").to(device)
        with torch.no_grad():
            logits = model(**inputs).logits
            probs = torch.softmax(logits, dim=1).cpu().numpy()
        all_probs.append(probs)
    return np.vstack(all_probs)

probs_xlmr, probs_mbert, probs_deberta = {}, {}, {}

for col in ["hindi_translit","tamil_translit","telugu_translit"]:
    probs_xlmr[col] = get_probs(full_df[col].tolist(), tok_xlmr, model_xlmr)
    probs_mbert[col] = get_probs(full_df[col].tolist(), tok_mbert, model_mbert)
    # probs_deberta[col] = get_probs(full_df[col].tolist(), tok_deberta, model_deberta)

def semantic_drift(e1, e2):
    return 1 - np.diag(cosine_similarity(e1, e2))

def jsd(p, q):
    return jensenshannon(p, q)**2

probs_eng = np.stack([
    1 - full_df["manipulative_label"].values,
    full_df["manipulative_label"].values
], axis=1)

def compute_all(emb, probs):
    res = {}
    for lang in ["hindi_translit","tamil_translit","telugu_translit"]:
        sem = semantic_drift(emb["english_text"], emb[lang])
        emo = np.array([jsd(p, q) for p, q in zip(probs_eng, probs[lang])])
        res[lang] = (sem.mean(), emo.mean())
    return res

res_xlmr = compute_all(emb_xlmr, probs_xlmr)
res_mbert = compute_all(emb_mbert, probs_mbert)
# res_deberta = compute_all(emb_deberta, probs_deberta)

# print("XLM-R:", res_xlmr)
print("mBERT:", res_mbert)
# print("DeBERTa:", res_deberta)

muril_path = train_and_save(
    "google/muril-base-cased",
    "muril_model",
    use_fp16=True
)
clear_gpu()

tok_muril, model_muril = load_model("muril_model")

emb_muril = {}

for col in ["english_text","hindi_translit","tamil_translit","telugu_translit"]:
    emb_muril[col] = get_embeddings(full_df[col].tolist(), tok_muril, model_muril)

probs_muril = {}

for col in ["hindi_translit","tamil_translit","telugu_translit"]:
    probs_muril[col] = get_probs(full_df[col].tolist(), tok_muril, model_muril)

res_muril = compute_all(emb_muril, probs_muril)

print("mBERT:", res_mbert)
print("MuRIL:", res_muril)

def train_and_save_rembert():
    clear_gpu()

    model_name = "google/rembert"
    save_name = "rembert_model"

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

    # 🔥 SAFE TOKENIZATION (fixed)
    train_enc = tokenizer(
        list(train_df['english_text']),
        truncation=True,
        padding=True,
        max_length=128
    )

    val_enc = tokenizer(
        list(val_df['english_text']),
        truncation=True,
        padding=True,
        max_length=128
    )

    train_ds = TextDataset(train_enc, list(train_df['manipulative_label']))
    val_ds   = TextDataset(val_enc, list(val_df['manipulative_label']))

    training_args = TrainingArguments(
        output_dir=save_name,
        num_train_epochs=2,
        per_device_train_batch_size=2,
        per_device_eval_batch_size=2,
        gradient_accumulation_steps=2,
        fp16=False,   # 🔥 keep OFF for safety
        eval_strategy="epoch",
        save_strategy="no"
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds
    )

    trainer.train()

    model.save_pretrained(save_name)
    tokenizer.save_pretrained(save_name)

    print("Saved RemBERT")
    return save_name

rembert_path = train_and_save_rembert()
clear_gpu()

tok_rembert, model_rembert = load_model("rembert_model")

def get_embeddings_rembert(texts, tokenizer, model):
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    all_embs = []
    for i in range(0, len(texts), 16):
        batch = texts[i:i+16]
        inputs = tokenizer(
            batch,
            padding=True,
            truncation=True,
            max_length=128,   # 🔥 FIX
            return_tensors="pt"
        ).to(device)

        with torch.no_grad():
            outputs = model.base_model(**inputs)
            emb = outputs.last_hidden_state.mean(dim=1).cpu().numpy()

        all_embs.append(emb)

    return np.vstack(all_embs)

emb_rembert = {}

for col in ["english_text","hindi_translit","tamil_translit","telugu_translit"]:
    emb_rembert[col] = get_embeddings_rembert(full_df[col].tolist(), tok_rembert, model_rembert)

def get_probs_rembert(texts, tokenizer, model):
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    all_probs = []
    for i in range(0, len(texts), 16):
        batch = texts[i:i+16]
        inputs = tokenizer(
            batch,
            padding=True,
            truncation=True,
            max_length=128,   # 🔥 FIX
            return_tensors="pt"
        ).to(device)

        with torch.no_grad():
            logits = model(**inputs).logits
            probs = torch.softmax(logits, dim=1).cpu().numpy()

        all_probs.append(probs)

    return np.vstack(all_probs)

probs_rembert = {}

for col in ["hindi_translit","tamil_translit","telugu_translit"]:
    probs_rembert[col] = get_probs_rembert(full_df[col].tolist(), tok_rembert, model_rembert)

res_rembert = compute_all(emb_rembert, probs_rembert)

print("mBERT:", res_mbert)
print("MuRIL:", res_muril)
print("RemBERT:", res_rembert)